### PR TITLE
add fr language

### PR DESCRIPTION
**Pull request by awerner25**
Hi,

I translated into french your plugin.

Regards.

### CODE REVIEW

**Comment by Findus23** [comment]
Hi,

Thanks for the contribution. Is the plugin working for you? As haveibeenpwned needs a (paid) API key to access this data now, I kind of abandoned this plugin: https://haveibeenpwned.com/API/Key

**Comment by awerner25** [comment]
Hi,

yes the plugin works.

**Comment by Findus23** [comment]
It seems like the paid key does not affect the password API used here. So it should indeed still work.

**Comment by Findus23** [comment]
Hi, 

Version 0.1.2 including your translation has been published: https://plugins.matomo.org/PasswordVerifier

Thanks again for your help.

**Pull request merged**
